{{- if and .Values.githubTool.enabled .Values.githubTool.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.githubTool.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tools.labels" . | nindent 4 }}
  {{- with .Values.githubTool.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
automountServiceAccountToken: {{ .Values.githubTool.serviceAccount.automount }}
{{- end }}
