{{- if and .Values.webFetch.enabled .Values.webFetch.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.webFetch.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tools.labels" . | nindent 4 }}
  {{- with .Values.webFetch.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
automountServiceAccountToken: {{ .Values.webFetch.serviceAccount.automount }}
{{- end }}
