{{- if and .Values.webSearch.enabled .Values.webSearch.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.webSearch.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tools.labels" . | nindent 4 }}
  {{- with .Values.webSearch.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.webSearch.serviceAccount.automount }}
{{- end }}
