/**
 * Copies shell/form_shell.html into the SHELL_HTML constant in
 * tool/helm_values_form.py.
 *
 * The Python tool has to be pasteable into Open WebUI's Tools workspace as one
 * file, so it cannot read the shell off disk -- but the HTML should still live in
 * a real .html file that an editor will highlight and a diff will read. This
 * script is the seam between those two facts, and tests/test_tool.py fails the
 * build if it has not been run.
 *
 * Run with --check to verify without writing (what CI does).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const shellPath = join(root, "shell", "form_shell.html");
const toolPath = join(root, "tool", "helm_values_form.py");

const BEGIN = "# >>> SHELL BEGIN (generated by scripts/sync-shell.mjs -- do not edit by hand)";
const END = "# <<< SHELL END";

const shell = readFileSync(shellPath, "utf8");
const tool = readFileSync(toolPath, "utf8");

const start = tool.indexOf(BEGIN);
const stop = tool.indexOf(END);
if (start < 0 || stop < 0 || stop < start) {
  console.error(`Could not find the SHELL BEGIN/END sentinels in ${toolPath}.`);
  process.exit(1);
}

// A Python raw triple-quoted string keeps the JS backslash escapes ("\n" inside
// the postMessage text) intact, so the two files stay byte-identical. The shell
// must therefore never contain a triple double-quote or end in a backslash.
if (shell.includes('"""')) {
  console.error("shell/form_shell.html contains a triple double-quote, which cannot be embedded in a Python raw string.");
  process.exit(1);
}
if (shell.endsWith("\\")) {
  console.error("shell/form_shell.html ends with a backslash, which a Python raw string cannot end with.");
  process.exit(1);
}

const block = `${BEGIN}\nSHELL_HTML = r"""${shell}"""\n`;
const next = tool.slice(0, start) + block + tool.slice(stop);

if (process.argv.includes("--check")) {
  if (next !== tool) {
    console.error(
      "tool/helm_values_form.py is out of sync with shell/form_shell.html.\n" +
        "Run `npm run sync-shell` in tools/helm-values-form.",
    );
    process.exit(1);
  }
  console.log("shell is in sync");
} else {
  if (next === tool) {
    console.log("shell already in sync");
  } else {
    writeFileSync(toolPath, next);
    console.log(`synced ${shell.length} bytes of shell into tool/helm_values_form.py`);
  }
}
