package rbac_test

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"github.com/controller-agent/temporal-engine/internal/rbac"
)

// Vector generated by agent-orchestrator's own mintCallerIdentityAssertion
// (apps/agent-orchestrator/src/rbac/caller-identity-assertion.ts) — same
// cross-implementation discipline as sender_assertion_test.go's tsVectors: an
// assertion minted by the TypeScript side must verify here.
func TestVerifyCallerIdentityAssertion_TypeScriptVector(t *testing.T) {
	assertion := "eyJzdWJqZWN0Ijoib3BlbndlYnVpOmFsaWNlIiwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInBlclVzZXIiOnRydWUsImV4cCI6MTcwMDAwMDMwMH0.2OvGNdQWfCb9P0Wge72LN_60Q2fPcYIpNHHXaTQm60Q"
	now := time.UnixMilli(1700000000000 - 100_000) // before the vector's exp

	subject, roles, perUser := rbac.VerifyCallerIdentityAssertion("s3cr3t", assertion, now)
	require.Equal(t, "openwebui:alice", subject)
	require.Equal(t, []string{"reader", "writer"}, roles)
	require.True(t, perUser)
}

func TestCallerIdentityAssertion_RoundTrip(t *testing.T) {
	now := time.Now()
	assertion := rbac.MintCallerIdentityAssertion("s3cr3t", "openwebui:bob", []string{"reader"}, true, rbac.DefaultAssertionTTL, now)

	subject, roles, perUser := rbac.VerifyCallerIdentityAssertion("s3cr3t", assertion, now)
	require.Equal(t, "openwebui:bob", subject)
	require.Equal(t, []string{"reader"}, roles)
	require.True(t, perUser)
}

func TestCallerIdentityAssertion_RoundTrip_NotPerUser(t *testing.T) {
	now := time.Now()
	assertion := rbac.MintCallerIdentityAssertion("s3cr3t", "client-integration-gateway", []string{"reader", "writer"}, false, rbac.DefaultAssertionTTL, now)

	subject, roles, perUser := rbac.VerifyCallerIdentityAssertion("s3cr3t", assertion, now)
	require.Equal(t, "client-integration-gateway", subject)
	require.Equal(t, []string{"reader", "writer"}, roles)
	require.False(t, perUser)
}

func TestVerifyCallerIdentityAssertion_WrongSecret(t *testing.T) {
	now := time.Now()
	assertion := rbac.MintCallerIdentityAssertion("s3cr3t", "openwebui:bob", []string{"reader"}, true, rbac.DefaultAssertionTTL, now)

	subject, roles, perUser := rbac.VerifyCallerIdentityAssertion("wrong-secret", assertion, now)
	require.Empty(t, subject)
	require.Nil(t, roles)
	require.False(t, perUser)
}

func TestVerifyCallerIdentityAssertion_Expired(t *testing.T) {
	now := time.Now()
	assertion := rbac.MintCallerIdentityAssertion("s3cr3t", "openwebui:bob", []string{"reader"}, true, time.Second, now.Add(-time.Hour))

	subject, roles, perUser := rbac.VerifyCallerIdentityAssertion("s3cr3t", assertion, now)
	require.Empty(t, subject)
	require.Nil(t, roles)
	require.False(t, perUser)
}
