package rbac_test

import (
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"durable-agents/internal/rbac"
)

// Vectors generated by agent-orchestrator's own mintSenderAssertion
// (apps/agent-orchestrator/src/rbac/sender-assertion.ts) — not by reading the
// code and reimplementing it. This is the whole point of the port: an
// assertion minted by the TypeScript gateway must verify here, and vice
// versa. If a future change breaks wire compatibility, these fail rather than
// integration-gateway's turns silently losing their sender identity and
// degrading to the shared service subject.
var tsVectors = []struct {
	name      string
	secret    string
	login     string
	ttl       time.Duration
	now       time.Time
	assertion string
}{
	{
		name:      "typical login",
		secret:    "s3cr3t",
		login:     "imaustink",
		ttl:       300 * time.Second,
		now:       time.UnixMilli(1754150400000),
		assertion: "eyJsb2dpbiI6ImltYXVzdGluayIsImV4cCI6MTc1NDE1MDcwMH0.oZOMvfsYo9nZYutOEI_fwjBMsoPW5Pbl6eVx1cU0XMI",
	},
	{
		name:      "short ttl",
		secret:    "s3cr3t",
		login:     "octocat",
		ttl:       60 * time.Second,
		now:       time.UnixMilli(1000000000000),
		assertion: "eyJsb2dpbiI6Im9jdG9jYXQiLCJleHAiOjEwMDAwMDAwNjB9.O2JCTWkt7GQy9xEskc4Y5-pj_Tc-FQJ32eagPAQp7II",
	},
	{
		// A bot login carries brackets, and the secret carries non-ASCII —
		// both would break a naive byte-length or charset assumption.
		name:      "bracketed login, non-ascii secret",
		secret:    "another-secret-with-Ünicode",
		login:     "dependabot[bot]",
		ttl:       300 * time.Second,
		now:       time.UnixMilli(1754150400000),
		assertion: "eyJsb2dpbiI6ImRlcGVuZGFib3RbYm90XSIsImV4cCI6MTc1NDE1MDcwMH0.8g2G8A5Iq9E1vywnFdgA2K1nWDONXnmUN9nJUlZGDdw",
	},
}

func TestMintMatchesTypeScriptByteForByte(t *testing.T) {
	for _, v := range tsVectors {
		t.Run(v.name, func(t *testing.T) {
			require.Equal(t, v.assertion, rbac.MintSenderAssertion(v.secret, v.login, v.ttl, v.now))
		})
	}
}

func TestVerifyAcceptsTypeScriptMintedAssertions(t *testing.T) {
	for _, v := range tsVectors {
		t.Run(v.name, func(t *testing.T) {
			// One second before expiry.
			at := v.now.Add(v.ttl - time.Second)
			require.Equal(t, v.login, rbac.VerifySenderAssertion(v.secret, v.assertion, at))
		})
	}
}

func TestVerifyFailsClosed(t *testing.T) {
	v := tsVectors[0]
	valid := v.now.Add(time.Minute)

	cases := []struct {
		name      string
		secret    string
		assertion string
		at        time.Time
	}{
		{"wrong secret", "not-the-secret", v.assertion, valid},
		{"no secret configured", "", v.assertion, valid},
		{"empty assertion", v.secret, "", valid},
		{"no separator", v.secret, "eyJsb2dpbiI6ImltYXVzdGluayJ9", valid},
		{"empty payload half", v.secret, ".sig", valid},
		{"empty signature half", v.secret, "eyJsb2dpbiI6ImEifQ.", valid},
		{"tampered signature", v.secret, v.assertion[:len(v.assertion)-1] + "X", valid},
		{"tampered payload", v.secret, "eyJsb2dpbiI6ImV2aWwiLCJleHAiOjE3NTQxNTA3MDB9." + v.assertion[len(v.assertion)-43:], valid},
		{"not base64", v.secret, "!!!.???", valid},
		// A three-part string is JWT-shaped, never something either
		// implementation mints; upstream's split-and-destructure would read
		// the first two parts, which is laxer than it needs to be.
		{"jwt-shaped", v.secret, "a.b.c", valid},
		{"expired", v.secret, v.assertion, v.now.Add(v.ttl + time.Second)},
		{"expired exactly at the boundary", v.secret, v.assertion, v.now.Add(v.ttl)},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			require.Empty(t, rbac.VerifySenderAssertion(c.secret, c.assertion, c.at))
		})
	}
}

// A signature is only as good as what it covers: the login must not be
// swappable for someone else's while the signature still checks out. This is
// the attack the header exists to stop — being handed another person's
// stored credentials by naming their login.
func TestVerifyRejectsALoginSwappedUnderAValidSignature(t *testing.T) {
	secret := "s3cr3t"
	now := time.UnixMilli(1754150400000)
	mine := rbac.MintSenderAssertion(secret, "imaustink", rbac.DefaultAssertionTTL, now)
	theirs := rbac.MintSenderAssertion(secret, "someone-else", rbac.DefaultAssertionTTL, now)

	mixed := mine[:strings.Index(mine, ".")] + theirs[strings.Index(theirs, "."):]
	require.Empty(t, rbac.VerifySenderAssertion(secret, mixed, now.Add(time.Minute)))
}

func TestRoundTrip(t *testing.T) {
	now := time.Now()
	a := rbac.MintSenderAssertion("shared", "octocat", rbac.DefaultAssertionTTL, now)
	require.Equal(t, "octocat", rbac.VerifySenderAssertion("shared", a, now))
	require.Empty(t, rbac.VerifySenderAssertion("shared", a, now.Add(rbac.DefaultAssertionTTL+time.Second)))
}
