{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "integration-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "integration-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.githubWebhookSecretKey }}: {{ .Values.secrets.githubWebhookSecret | quote }}
  {{ .Values.secrets.orchestratorTokenKey }}: {{ .Values.secrets.orchestratorToken | quote }}
  {{- if .Values.secrets.githubToken }}
  {{ .Values.secrets.githubTokenKey }}: {{ .Values.secrets.githubToken | quote }}
  {{- end }}
  {{- if .Values.secrets.githubAppId }}
  {{ .Values.secrets.githubAppIdKey }}: {{ .Values.secrets.githubAppId | quote }}
  {{ .Values.secrets.githubAppPrivateKeyKey }}: {{ .Values.secrets.githubAppPrivateKey | quote }}
  {{ .Values.secrets.githubAppInstallationIdKey }}: {{ .Values.secrets.githubAppInstallationId | quote }}
  {{- end }}
  {{- if .Values.identityLink.enabled }}
  {{ .Values.secrets.identityLinkEncryptionKeyKey }}: {{ .Values.secrets.identityLinkEncryptionKey | quote }}
  {{ .Values.secrets.identityLinkTokenKey }}: {{ .Values.secrets.identityLinkToken | quote }}
  {{ .Values.secrets.githubAppClientSecretKey }}: {{ .Values.secrets.githubAppClientSecret | quote }}
  {{ .Values.secrets.identityLinkStateSecretKey }}: {{ .Values.secrets.identityLinkStateSecret | quote }}
  {{- end }}
{{- end }}
