# This rule is not used by the project tool-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the tool.recipe-agent.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tool-controller
    app.kubernetes.io/managed-by: kustomize
  name: toolrun-editor-role
rules:
- apiGroups:
  - tool.recipe-agent.dev
  resources:
  - toolruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tool.recipe-agent.dev
  resources:
  - toolruns/status
  verbs:
  - get
