"""
title: Helm Values Form
author: Bitovi
author_url: https://github.com/imaustink/agent-controller
funding_url: https://github.com/imaustink/agent-controller
version: 0.1.0
required_open_webui_version: 0.6.0
license: MIT
description: Renders a Helm chart's values.schema.json as a form embedded in the chat, and turns what the user fills in into a minimal values.yaml containing only the fields that differ from the chart defaults.
"""

# How this works, because the mechanism is not obvious:
#
# show_values_form returns an HTMLResponse carrying `Content-Disposition:
# inline`. Open WebUI's middleware sees that header, pulls the HTML out, and
# renders it in a sandboxed iframe inside the assistant message. The iframe
# posts the generated YAML back to the parent's chat input, so it arrives as the
# user's next message.
#
# Everything the iframe needs is inlined into that HTML. It cannot fetch: a
# sandboxed frame without same-origin access has an opaque origin, so module
# imports would go out with `Origin: null`. The cost of inlining is that the
# bundle and the pruned schema are persisted into the chat database on every
# message -- which is what the two byte budgets in Valves are defending.

import copy
import html as html_mod
import json
import os
from typing import Any, Dict, List, Optional, Tuple

from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field

BUNDLE_MARKER = "/*__BUNDLE__*/"
CONFIG_MARKER = "/*__CONFIG__*/"

# --- shell -------------------------------------------------------------------
# Verbatim copy of shell/form_shell.html. It lives here as a constant so this
# file stays pasteable into Open WebUI's Tools workspace on its own; the file on
# disk is the source of truth. `npm run sync-shell` rewrites the block between
# the sentinels below, and tests/test_tool.py fails if the two drift apart.
# >>> SHELL BEGIN (generated by scripts/sync-shell.mjs -- do not edit by hand)
SHELL_HTML = r"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Helm values</title>
  </head>
  <body>
    <div id="root"></div>

    <!--
      Two block-comment markers below are replaced by tool/helm_values_form.py
      using str.replace (not an f-string or .format -- this file is dense with
      braces and both would fight it):

        the BUNDLE marker, inside the first script tag, becomes the built IIFE
        from dist/owui-form.js;

        the CONFIG marker becomes the JSON-serialized FormConfig, with every
        less-than sign rewritten to its JSON unicode escape first, so that a
        chart description containing a closing script tag cannot terminate this
        script early.

      Both markers are written out only once each, at their substitution sites:
      str.replace hits every occurrence, so naming them literally in this
      comment would inject the bundle in here too.
    -->
    <script>
      /*__BUNDLE__*/
    </script>
    <script>
      (function () {
        var CFG = /*__CONFIG__*/;
        var root = document.getElementById("root");

        try {
          OWUIForm.render(root, CFG, function (yaml) {
            var text =
              "Values for **" + CFG.chart + "**\n\n" + "```yaml\n" + yaml + "\n```";
            // Arrives as the user's next chat message. Open WebUI shows a
            // confirmation dialog first, because this is a cross-origin prompt
            // submission from a sandboxed frame.
            parent.postMessage({ type: "input:prompt:submit", text: text }, "*");
          });
        } catch (e) {
          // A blank embed is the worst outcome: it looks like the tool is
          // broken, with no way to tell why. Say something, in plain text.
          root.textContent = "This form failed to render: " + (e && e.message ? e.message : e);
        }

        // Height reporting is mandatory, not an optimization. With same-origin
        // access off (the default) the parent cannot measure this document, so
        // without these messages the embed is clipped to a small default height
        // with its own scrollbar. Collapsible sections mean the height changes
        // constantly, hence the observer as well as the load handler.
        function measure() {
          // Deliberately NOT document.documentElement.scrollHeight: that value is
          // floored at the viewport height, so once the parent has sized this
          // frame to N it can never report anything smaller than N -- collapsing
          // a section would leave dead space that never goes away. The content
          // element's own box is independent of how tall the frame currently is.
          var box = root ? root.getBoundingClientRect().height : 0;
          var body = document.body ? document.body.scrollHeight : 0;
          return Math.ceil(Math.max(box, body));
        }

        var last = -1;
        function report() {
          var h = measure();
          if (h === last || h === 0) return;
          last = h;
          parent.postMessage({ type: "iframe:height", height: h }, "*");
        }
        window.addEventListener("load", report);
        if (typeof ResizeObserver === "function") {
          new ResizeObserver(report).observe(document.body);
        }
        // Toggling a <details> resizes the body, but the observer can lag a
        // frame behind layout; this makes expand/collapse feel immediate.
        document.addEventListener("toggle", report, true);
        // One measurement now so a browser without ResizeObserver still gets a
        // size, and one after layout settles -- the synchronous value can be
        // taken before the frame has its final width, which wraps everything and
        // overestimates badly.
        report();
        if (typeof requestAnimationFrame === "function") requestAnimationFrame(report);
      })();
    </script>
  </body>
</html>
"""
# <<< SHELL END
# --- end shell ---------------------------------------------------------------


class Tools:
    class Valves(BaseModel):
        bundle_path: str = Field(
            default="/app/backend/data/helm-values-form/owui-form.js",
            description="Filesystem path to the built renderer bundle (dist/owui-form.js).",
        )
        charts_dir: str = Field(
            default="/app/backend/data/helm-values-form/charts",
            description="Directory holding <chart>.form.json allowlists and their .schema.json files.",
        )
        max_bundle_bytes: int = Field(
            default=32768,
            description=(
                "Refuse to render if the bundle exceeds this. The bundle is stored in the "
                "chat database once per message, so this is a per-message cost."
            ),
        )
        max_config_bytes: int = Field(
            default=65536,
            description=(
                "Refuse to render if the serialized schema exceeds this. A chart that blows "
                "this budget needs a tighter `include` allowlist, not a bigger number."
            ),
        )

    def __init__(self) -> None:
        self.valves = self.Valves()

    # --- tools ---------------------------------------------------------------

    def list_charts(self) -> str:
        """
        List the Helm charts that have a values form available, with their titles.

        Call this when the user asks what can be configured, or when they name a
        chart that show_values_form did not recognize.
        """
        charts = self._available()
        if not charts:
            return (
                f"No charts are configured. The charts directory "
                f"({self.valves.charts_dir}) has no <name>.form.json files in it."
            )
        lines = ["Charts with a values form available:"]
        for name, title in charts:
            lines.append(f"- {name}" + (f" ({title})" if title and title != name else ""))
        return "\n".join(lines)

    def show_values_form(self, chart: str) -> tuple:
        """
        Display an interactive form for a Helm chart's values in the chat, and
        wait for the user to fill it in and submit it.

        :param chart: Name of the chart to configure, e.g. "temporal-worker". Use list_charts to see what is available.
        """
        try:
            form = self._load_form(chart)
        except FileNotFoundError:
            # A plain string, never an exception: an unknown chart is a normal
            # conversational turn, and the model can recover from it by offering
            # the real names.
            known = ", ".join(name for name, _ in self._available()) or "(none configured)"
            return (
                f"There is no values form for a chart named '{chart}'. "
                f"Available charts: {known}."
            )
        except (OSError, ValueError) as exc:
            return f"Could not load the values form for '{chart}': {exc}"

        try:
            schema = self._load_schema(form)
        except (OSError, ValueError) as exc:
            return f"Could not load the schema for '{chart}': {exc}"

        include = [p for p in (form.get("include") or []) if isinstance(p, str)]
        pruned, missing = _prune_schema(schema, include)
        if missing:
            # Hard error, not a silent skip. A path that stopped resolving means
            # the chart moved out from under the allowlist, and a form that
            # quietly dropped the field would emit a values file missing an
            # override the user asked for.
            return (
                f"The field allowlist for '{chart}' no longer matches its schema. "
                f"These paths in {chart}.form.json do not resolve: {', '.join(missing)}. "
                f"The chart was probably bumped; the allowlist needs updating before "
                f"this form can be shown."
            )

        cfg: Dict[str, Any] = {
            "chart": form.get("chart") or chart,
            "title": form.get("title") or chart,
            "schema": pruned,
            "include": include,
        }
        if form.get("description"):
            cfg["description"] = form["description"]
        if form.get("submitLabel"):
            cfg["submitLabel"] = form["submitLabel"]
        if form.get("chartVersion"):
            cfg["chartVersion"] = form["chartVersion"]

        try:
            page = self._build_html(cfg)
        except (OSError, ValueError) as exc:
            return f"Could not build the values form for '{chart}': {exc}"

        context = {
            "status": "form_displayed",
            "chart": cfg["chart"],
            "title": cfg["title"],
            "included_paths": include or ["(entire schema)"],
            # Without this the model reliably starts interviewing the user field
            # by field while the form sits ignored above the message.
            "instructions": (
                f"An interactive form for the '{cfg['chart']}' chart is now displayed above "
                "this message. Do NOT ask the user for these values conversationally, and do "
                "not list the fields. Reply with one short sentence telling them to fill in "
                "the form and submit it. Then stop and wait: their submission will arrive as "
                "their next message, containing a YAML code block. When it does, call "
                "record_values with the chart name and the dotted paths that appear in that "
                "YAML, so the live form is replaced by a static receipt."
            ),
        }
        return HTMLResponse(page, headers={"Content-Disposition": "inline"}), context

    async def record_values(
        self,
        chart: str,
        paths: str = "",
        __event_emitter__=None,
    ) -> str:
        """
        Replace the live values form with a static receipt, after the user has
        submitted it. Call this once you have received their YAML.

        :param chart: Name of the chart whose form was submitted.
        :param paths: The dotted paths that appear in the submitted YAML, comma-separated, e.g. "image.tag, resources.limits.memory". Leave empty if the submission overrode nothing.
        """
        listed = [p.strip() for p in paths.replace("\n", ",").split(",") if p.strip()]

        if __event_emitter__ is None:
            # Nothing to replace without an emitter; say so rather than claiming
            # the form was cleaned up.
            return (
                f"Recorded values for {chart}, but the live form could not be replaced "
                "(no event emitter was available in this context)."
            )

        await __event_emitter__(
            {
                # The short name. The `chat:message:embeds` alias renders
                # identically but is NOT persisted, so a reloaded chat would show
                # the original still-clickable form again.
                "type": "embeds",
                "data": {
                    # replace: True overwrites the message's entire embeds array
                    # rather than appending to it.
                    "embeds": [_receipt_html(chart, listed)],
                    "replace": True,
                },
            }
        )

        if listed:
            return (
                f"Recorded {len(listed)} override(s) for {chart}: {', '.join(listed)}. "
                "The form has been replaced with a receipt."
            )
        return (
            f"Recorded the submission for {chart}; it overrode nothing, so every field "
            "matches the chart defaults. The form has been replaced with a receipt."
        )

    # --- internals -----------------------------------------------------------

    def _available(self) -> List[Tuple[str, str]]:
        out: List[Tuple[str, str]] = []
        try:
            names = sorted(os.listdir(self.valves.charts_dir))
        except OSError:
            return out
        for entry in names:
            if not entry.endswith(".form.json"):
                continue
            name = entry[: -len(".form.json")]
            title = name
            try:
                with open(os.path.join(self.valves.charts_dir, entry), encoding="utf-8") as fh:
                    doc = json.load(fh)
                if isinstance(doc, dict):
                    title = str(doc.get("title") or doc.get("chart") or name)
            except (OSError, ValueError):
                # A broken sidecar should not hide the charts that do work.
                title = f"{name} (unreadable form.json)"
            out.append((name, title))
        return out

    def _load_form(self, chart: str) -> Dict[str, Any]:
        path = os.path.join(self.valves.charts_dir, f"{_safe_name(chart)}.form.json")
        if not os.path.isfile(path):
            raise FileNotFoundError(path)
        with open(path, encoding="utf-8") as fh:
            doc = json.load(fh)
        if not isinstance(doc, dict):
            raise ValueError(f"{path} does not contain a JSON object")
        return doc

    def _load_schema(self, form: Dict[str, Any]) -> Dict[str, Any]:
        rel = form.get("schema")
        if not isinstance(rel, str) or rel == "":
            raise ValueError("the form.json has no `schema` field")
        path = os.path.join(self.valves.charts_dir, _safe_name(rel))
        with open(path, encoding="utf-8") as fh:
            doc = json.load(fh)
        if not isinstance(doc, dict):
            raise ValueError(f"{path} does not contain a JSON object")
        return doc

    def _build_html(self, cfg: Dict[str, Any]) -> str:
        with open(self.valves.bundle_path, encoding="utf-8") as fh:
            bundle = fh.read()

        size = len(bundle.encode("utf-8"))
        if size > self.valves.max_bundle_bytes:
            raise ValueError(
                f"the renderer bundle is {size} bytes, over the {self.valves.max_bundle_bytes}-byte "
                f"budget (max_bundle_bytes). It is stored in the chat database once per message."
            )
        if "</script" in bundle.lower():
            raise ValueError(
                "the renderer bundle contains a closing script tag, which would terminate the "
                "inline script early"
            )

        config = json.dumps(cfg, separators=(",", ":"))
        cfg_size = len(config.encode("utf-8"))
        if cfg_size > self.valves.max_config_bytes:
            raise ValueError(
                f"the serialized schema is {cfg_size} bytes, over the "
                f"{self.valves.max_config_bytes}-byte budget (max_config_bytes). Tighten the "
                f"`include` allowlist in the form.json rather than raising the budget."
            )
        # Chart descriptions contain HTML more often than you would expect, and a
        # `</script>` anywhere in the serialized config would end the script tag
        # early. Escaping every `<` is the whole fix.
        config = config.replace("<", "\\u003c")

        if BUNDLE_MARKER not in SHELL_HTML or CONFIG_MARKER not in SHELL_HTML:
            raise ValueError("the embedded shell is missing its substitution markers")

        # str.replace, never an f-string or .format: the shell is dense with
        # braces and both would fight it.
        return SHELL_HTML.replace(BUNDLE_MARKER, bundle).replace(CONFIG_MARKER, config)


def _safe_name(name: str) -> str:
    """Keeps a chart name from walking out of charts_dir."""
    return os.path.basename(name.strip())


# --- schema pruning ----------------------------------------------------------


def _defs_of(root: Dict[str, Any]) -> Dict[str, Any]:
    merged: Dict[str, Any] = {}
    for key in ("definitions", "$defs"):
        section = root.get(key)
        if isinstance(section, dict):
            merged.update(section)
    return merged


def _resolve(node: Any, root: Dict[str, Any], seen: Optional[set] = None) -> Optional[Dict[str, Any]]:
    """
    Follows local `$ref` chains. Remote refs return None -- the renderer will not
    fetch them, so neither will we.
    """
    if not isinstance(node, dict):
        return None
    ref = node.get("$ref")
    if not isinstance(ref, str):
        return node
    seen = seen or set()
    if ref in seen or not ref.startswith("#/"):
        return None
    seen.add(ref)

    cur: Any = root
    for token in ref[2:].split("/"):
        token = token.replace("~1", "/").replace("~0", "~")
        if not isinstance(cur, dict) or token not in cur:
            return None
        cur = cur[token]
    if not isinstance(cur, dict):
        return None
    return _resolve(cur, root, seen) if "$ref" in cur else cur


def _collect_refs(node: Any, found: set) -> None:
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            found.add(ref)
        for value in node.values():
            _collect_refs(value, found)
    elif isinstance(node, list):
        for value in node:
            _collect_refs(value, found)


def _carry_defs(pruned: Dict[str, Any], root: Dict[str, Any]) -> None:
    """
    Copies across only the `$defs`/`definitions` entries the pruned tree can
    actually reach, transitively. Dragging the whole definitions block along
    would work too, but it counts against max_config_bytes for no benefit.
    """
    if not _defs_of(root):
        return

    wanted: set = set()
    _collect_refs(pruned, wanted)
    # Bucketed by the container each ref actually named, so a chart using
    # `definitions` and one using `$defs` each get back exactly the spelling
    # their own refs point at. Emitting both spellings would resolve too, but it
    # would serialize every definition twice against max_config_bytes.
    keep: Dict[str, Dict[str, Any]] = {"$defs": {}, "definitions": {}}
    while wanted:
        ref = wanted.pop()
        if not ref.startswith("#/"):
            continue
        parts = ref[2:].split("/")
        # Only the two standard containers; anything else is left as a dangling
        # ref, which the renderer reports as an unsupported field.
        if len(parts) != 2 or parts[0] not in keep:
            continue
        container, name = parts[0], parts[1].replace("~1", "/").replace("~0", "~")
        source = root.get(container)
        if not isinstance(source, dict) or name not in source or name in keep[container]:
            continue
        keep[container][name] = copy.deepcopy(source[name])
        nested: set = set()
        _collect_refs(keep[container][name], nested)
        wanted |= nested

    for container, entries in keep.items():
        if entries:
            # Sorted so the same schema always serializes to the same bytes.
            pruned[container] = {k: entries[k] for k in sorted(entries)}


def _prune_schema(
    root: Dict[str, Any], include: List[str]
) -> Tuple[Dict[str, Any], List[str]]:
    """
    Narrows `root` to exactly the dotted paths in `include`, keeping the
    intermediate object nodes needed to reach them.

    Returns (pruned schema, unresolved paths). An unresolved path is a hard
    error at the call site: it is how a stale allowlist announces itself after a
    chart bump.

    An empty `include` means render everything, which the README discourages --
    a full Bitnami schema is several hundred fields and unusable as a form.
    """
    if not include:
        return copy.deepcopy(root), []

    skip = ("properties", "required", "$defs", "definitions")
    pruned: Dict[str, Any] = {k: copy.deepcopy(v) for k, v in root.items() if k not in skip}
    pruned["properties"] = {}
    # Track which children survived at each level so `required` can be filtered
    # down to fields the form actually renders.
    survivors: Dict[int, Any] = {}
    missing: List[str] = []

    for path in include:
        segments = [s for s in path.split(".") if s != ""]
        if not segments:
            missing.append(path)
            continue

        src: Optional[Dict[str, Any]] = _resolve(root, root)
        dst: Dict[str, Any] = pruned
        chain: List[Tuple[Dict[str, Any], Dict[str, Any]]] = [(pruned, src or {})]
        ok = True

        for index, segment in enumerate(segments):
            src_props = (src or {}).get("properties")
            if not isinstance(src_props, dict) or segment not in src_props:
                # Includes the case of a path reaching into a free-form map's key
                # space (`podAnnotations.foo`), which is not a schema property.
                ok = False
                break
            child_raw = src_props[segment]
            child = _resolve(child_raw, root)
            if child is None:
                ok = False
                break

            dst_props = dst.setdefault("properties", {})
            if index == len(segments) - 1:
                # Leaf: keep it exactly as written, refs included. _carry_defs
                # brings along whatever those refs point at.
                dst_props[segment] = copy.deepcopy(child_raw)
            else:
                node = dst_props.get(segment)
                if not isinstance(node, dict) or "properties" not in node:
                    node = {k: copy.deepcopy(v) for k, v in child.items() if k not in skip}
                    node["properties"] = {}
                    dst_props[segment] = node
                dst = node
                src = child
                chain.append((node, child))

        if ok:
            for node, source in chain:
                survivors.setdefault(id(node), (node, source))
        else:
            missing.append(path)

    for node, source in survivors.values():
        properties = node.get("properties") or {}

        # Reorder to the source schema's declaration order. Without this, both the
        # form and the emitted YAML come out in the order the paths happen to
        # appear in `include` -- so reordering the allowlist would reshuffle a
        # values file that is checked into git, and the form would list fields in
        # an order the chart never asked for.
        source_properties = source.get("properties")
        if isinstance(source_properties, dict):
            node["properties"] = {
                key: properties[key] for key in source_properties if key in properties
            }
            # Anything not in the source (there should be nothing) keeps its place
            # at the end rather than being dropped.
            for key in properties:
                if key not in node["properties"]:
                    node["properties"][key] = properties[key]
            properties = node["properties"]

        required = source.get("required")
        if isinstance(required, list):
            kept = [r for r in required if r in properties]
            if kept:
                node["required"] = kept

    _carry_defs(pruned, root)
    return pruned, missing


# --- receipt -----------------------------------------------------------------


def _receipt_html(chart: str, paths: List[str]) -> str:
    """
    The static replacement for a submitted form.

    A live form left in a reloaded chat is a trap: it looks clickable, but
    submitting it a second time re-sends stale values. This is inert -- no
    inputs, no handlers -- but it still needs the height postMessage, because
    the parent cannot measure a cross-origin iframe either way.
    """
    rows = (
        "".join(
            f"<li><code>{html_mod.escape(p)}</code></li>" for p in paths
        )
        or "<li>Nothing was overridden; every field matched the chart default.</li>"
    )
    return f"""<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
:root{{--c:#18181b;--m:#71717a;--b:#e4e4e7;--bg:#fafafa}}
@media (prefers-color-scheme:dark){{:root{{--c:#f4f4f5;--m:#a1a1aa;--b:#3f3f46;--bg:#1f1f23}}}}
body{{margin:0;font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:var(--c)}}
.r{{border:1px solid var(--b);background:var(--bg);border-radius:8px;padding:12px 14px;margin:0}}
.h{{font-weight:600;margin:0 0 2px}}
.s{{color:var(--m);font-size:12px;margin:0 0 8px}}
ul{{margin:0;padding-left:20px}}
code{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}}
</style>
<div class="r">
  <p class="h">Values submitted &middot; {html_mod.escape(chart)}</p>
  <p class="s">Overridden paths:</p>
  <ul>{rows}</ul>
</div>
<script>
  (function () {{
    var last = -1;
    function report() {{
      var h = document.documentElement.scrollHeight;
      if (h === last) return;
      last = h;
      parent.postMessage({{ type: "iframe:height", height: h }}, "*");
    }}
    window.addEventListener("load", report);
    if (typeof ResizeObserver === "function") new ResizeObserver(report).observe(document.body);
    report();
  }})();
</script>"""
