// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agentcontroller/protocol/v1/agent_protocol.proto

package protocolv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// agent -> orchestrator.
type AgentUpMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation id = the agent run's name; shared by every message of one run.
	AgentRunId *string `protobuf:"bytes,1,opt,name=agent_run_id,proto3,oneof" json:"agent_run_id,omitempty"`
	// Monotonic per-direction sequence number; ordering and dedupe.
	Seq *uint32 `protobuf:"varint,2,opt,name=seq,proto3,oneof" json:"seq,omitempty"`
	// ISO 8601 emission timestamp.
	Ts   *string `protobuf:"bytes,3,opt,name=ts,proto3,oneof" json:"ts,omitempty"`
	Type *string `protobuf:"bytes,4,opt,name=type,proto3,oneof" json:"type,omitempty"`
	// progress / warning / reply / failed.
	Stage   *string  `protobuf:"bytes,5,opt,name=stage,proto3,oneof" json:"stage,omitempty"`
	Message *string  `protobuf:"bytes,6,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Pct     *float64 `protobuf:"fixed64,7,opt,name=pct,proto3,oneof" json:"pct,omitempty"`
	// reply: `final: false` means the agent awaits a further prompt (including
	// when `message` is a question for the user); `final: true` means the task
	// is complete and the agent exits after this. `result` is an optional
	// structured outcome for non-chat consumers.
	Final  *bool           `protobuf:"varint,8,opt,name=final,proto3,oneof" json:"final,omitempty"`
	Result *structpb.Value `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	// failed.
	Code *string `protobuf:"bytes,10,opt,name=code,proto3,oneof" json:"code,omitempty"`
	// opencode_event: one raw event from the agent's local session server,
	// forwarded verbatim for a live viewer. Best-effort.
	Event *structpb.Value `protobuf:"bytes,11,opt,name=event,proto3" json:"event,omitempty"`
	// opencode_response: the reply to a down `opencode_request`, correlated by
	// requestId.
	RequestId *string         `protobuf:"bytes,12,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	Status    *int32          `protobuf:"varint,13,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Body      *structpb.Value `protobuf:"bytes,14,opt,name=body,proto3" json:"body,omitempty"`
	// session_idle: the agent has replied but stays resident (and tunnelable)
	// until this ISO 8601 time unless it sees more activity first.
	LiveUntil *string `protobuf:"bytes,15,opt,name=live_until,json=liveUntil,proto3,oneof" json:"live_until,omitempty"`
	// session_ended: the agent is about to exit.
	Reason *string `protobuf:"bytes,16,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// tool_call: the agent's own loop calling a tool it was granted. Answered
	// by a down `tool_result` with the same callId; several may be outstanding.
	CallId        *string `protobuf:"bytes,17,opt,name=call_id,json=callId,proto3,oneof" json:"call_id,omitempty"`
	Tool          *string `protobuf:"bytes,18,opt,name=tool,proto3,oneof" json:"tool,omitempty"`
	Input         *string `protobuf:"bytes,19,opt,name=input,proto3,oneof" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUpMessage) Reset() {
	*x = AgentUpMessage{}
	mi := &file_agentcontroller_protocol_v1_agent_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpMessage) ProtoMessage() {}

func (x *AgentUpMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentcontroller_protocol_v1_agent_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpMessage.ProtoReflect.Descriptor instead.
func (*AgentUpMessage) Descriptor() ([]byte, []int) {
	return file_agentcontroller_protocol_v1_agent_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *AgentUpMessage) GetAgentRunId() string {
	if x != nil && x.AgentRunId != nil {
		return *x.AgentRunId
	}
	return ""
}

func (x *AgentUpMessage) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *AgentUpMessage) GetTs() string {
	if x != nil && x.Ts != nil {
		return *x.Ts
	}
	return ""
}

func (x *AgentUpMessage) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *AgentUpMessage) GetStage() string {
	if x != nil && x.Stage != nil {
		return *x.Stage
	}
	return ""
}

func (x *AgentUpMessage) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *AgentUpMessage) GetPct() float64 {
	if x != nil && x.Pct != nil {
		return *x.Pct
	}
	return 0
}

func (x *AgentUpMessage) GetFinal() bool {
	if x != nil && x.Final != nil {
		return *x.Final
	}
	return false
}

func (x *AgentUpMessage) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AgentUpMessage) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *AgentUpMessage) GetEvent() *structpb.Value {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentUpMessage) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *AgentUpMessage) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *AgentUpMessage) GetBody() *structpb.Value {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentUpMessage) GetLiveUntil() string {
	if x != nil && x.LiveUntil != nil {
		return *x.LiveUntil
	}
	return ""
}

func (x *AgentUpMessage) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *AgentUpMessage) GetCallId() string {
	if x != nil && x.CallId != nil {
		return *x.CallId
	}
	return ""
}

func (x *AgentUpMessage) GetTool() string {
	if x != nil && x.Tool != nil {
		return *x.Tool
	}
	return ""
}

func (x *AgentUpMessage) GetInput() string {
	if x != nil && x.Input != nil {
		return *x.Input
	}
	return ""
}

// orchestrator -> agent.
type AgentDownMessage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AgentRunId *string                `protobuf:"bytes,1,opt,name=agent_run_id,proto3,oneof" json:"agent_run_id,omitempty"`
	Seq        *uint32                `protobuf:"varint,2,opt,name=seq,proto3,oneof" json:"seq,omitempty"`
	Ts         *string                `protobuf:"bytes,3,opt,name=ts,proto3,oneof" json:"ts,omitempty"`
	Type       *string                `protobuf:"bytes,4,opt,name=type,proto3,oneof" json:"type,omitempty"`
	// prompt: a user turn -- the initial goal or any follow-up.
	Message *string `protobuf:"bytes,5,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// cancel: stop and exit.
	Reason *string `protobuf:"bytes,6,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// signal: a generic out-of-band control signal (extension point).
	Name *string         `protobuf:"bytes,7,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Data *structpb.Value `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	// opencode_request: an HTTP call to forward into the agent's local session
	// server; answered by an up `opencode_response` with the same requestId.
	RequestId *string         `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	Method    *string         `protobuf:"bytes,10,opt,name=method,proto3,oneof" json:"method,omitempty"`
	Path      *string         `protobuf:"bytes,11,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Body      *structpb.Value `protobuf:"bytes,12,opt,name=body,proto3" json:"body,omitempty"`
	// reply_ack: confirms the up `reply`/`failed` with this seq was received.
	// The agent holds its concluding message, re-offering it, until acked, so a
	// lost publish (fire-and-forget transport, receiver restarting) does not
	// lose the turn's outcome. Narration is deliberately never acked.
	AckSeq *uint32 `protobuf:"varint,13,opt,name=ack_seq,json=ackSeq,proto3,oneof" json:"ack_seq,omitempty"`
	// tool_result: the answer to an up `tool_call` with the same callId.
	// `result` is meaningful when ok, `error` when not.
	CallId        *string         `protobuf:"bytes,14,opt,name=call_id,json=callId,proto3,oneof" json:"call_id,omitempty"`
	Ok            *bool           `protobuf:"varint,15,opt,name=ok,proto3,oneof" json:"ok,omitempty"`
	Result        *structpb.Value `protobuf:"bytes,16,opt,name=result,proto3" json:"result,omitempty"`
	Error         *string         `protobuf:"bytes,17,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDownMessage) Reset() {
	*x = AgentDownMessage{}
	mi := &file_agentcontroller_protocol_v1_agent_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDownMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDownMessage) ProtoMessage() {}

func (x *AgentDownMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentcontroller_protocol_v1_agent_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDownMessage.ProtoReflect.Descriptor instead.
func (*AgentDownMessage) Descriptor() ([]byte, []int) {
	return file_agentcontroller_protocol_v1_agent_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *AgentDownMessage) GetAgentRunId() string {
	if x != nil && x.AgentRunId != nil {
		return *x.AgentRunId
	}
	return ""
}

func (x *AgentDownMessage) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *AgentDownMessage) GetTs() string {
	if x != nil && x.Ts != nil {
		return *x.Ts
	}
	return ""
}

func (x *AgentDownMessage) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *AgentDownMessage) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *AgentDownMessage) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *AgentDownMessage) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AgentDownMessage) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AgentDownMessage) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *AgentDownMessage) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *AgentDownMessage) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *AgentDownMessage) GetBody() *structpb.Value {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentDownMessage) GetAckSeq() uint32 {
	if x != nil && x.AckSeq != nil {
		return *x.AckSeq
	}
	return 0
}

func (x *AgentDownMessage) GetCallId() string {
	if x != nil && x.CallId != nil {
		return *x.CallId
	}
	return ""
}

func (x *AgentDownMessage) GetOk() bool {
	if x != nil && x.Ok != nil {
		return *x.Ok
	}
	return false
}

func (x *AgentDownMessage) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AgentDownMessage) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_agentcontroller_protocol_v1_agent_protocol_proto protoreflect.FileDescriptor

const file_agentcontroller_protocol_v1_agent_protocol_proto_rawDesc = "" +
	"\n" +
	"0agentcontroller/protocol/v1/agent_protocol.proto\x12\x1bagentcontroller.protocol.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf0\x10\n" +
	"\x0eAgentUpMessage\x12/\n" +
	"\fagent_run_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01H\x00R\fagent_run_id\x88\x01\x01\x12\x1d\n" +
	"\x03seq\x18\x02 \x01(\rB\x06\xbaH\x03\xc8\x01\x01H\x01R\x03seq\x88\x01\x01\x12\x1b\n" +
	"\x02ts\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01H\x02R\x02ts\x88\x01\x01\x12\x95\x01\n" +
	"\x04type\x18\x04 \x01(\tB|\xbaHy\xc8\x01\x01rtR\x05readyR\bprogressR\awarningR\x05replyR\x06failedR\x0eopencode_eventR\x11opencode_responseR\fsession_idleR\rsession_endedR\ttool_callH\x03R\x04type\x88\x01\x01\x12\x19\n" +
	"\x05stage\x18\x05 \x01(\tH\x04R\x05stage\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x06 \x01(\tH\x05R\amessage\x88\x01\x01\x12.\n" +
	"\x03pct\x18\a \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00Y@)\x00\x00\x00\x00\x00\x00\x00\x00H\x06R\x03pct\x88\x01\x01\x12\x19\n" +
	"\x05final\x18\b \x01(\bH\aR\x05final\x88\x01\x01\x12.\n" +
	"\x06result\x18\t \x01(\v2\x16.google.protobuf.ValueR\x06result\x12\x17\n" +
	"\x04code\x18\n" +
	" \x01(\tH\bR\x04code\x88\x01\x01\x12,\n" +
	"\x05event\x18\v \x01(\v2\x16.google.protobuf.ValueR\x05event\x12\"\n" +
	"\n" +
	"request_id\x18\f \x01(\tH\tR\trequestId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\r \x01(\x05H\n" +
	"R\x06status\x88\x01\x01\x12*\n" +
	"\x04body\x18\x0e \x01(\v2\x16.google.protobuf.ValueR\x04body\x12\"\n" +
	"\n" +
	"live_until\x18\x0f \x01(\tH\vR\tliveUntil\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x10 \x01(\tH\fR\x06reason\x88\x01\x01\x12\x1c\n" +
	"\acall_id\x18\x11 \x01(\tH\rR\x06callId\x88\x01\x01\x12\x17\n" +
	"\x04tool\x18\x12 \x01(\tH\x0eR\x04tool\x88\x01\x01\x12\x19\n" +
	"\x05input\x18\x13 \x01(\tH\x0fR\x05input\x88\x01\x01:\xaf\t\xbaH\xab\t\x1aw\n" +
	"\"agent_up.progress_requires_message\x12#a progress message requires message\x1a,this.type != 'progress' || has(this.message)\x1at\n" +
	"!agent_up.warning_requires_message\x12\"a warning message requires message\x1a+this.type != 'warning' || has(this.message)\x1a\x8f\x01\n" +
	")agent_up.reply_requires_message_and_final\x12\"a reply requires message and final\x1a>this.type != 'reply' || (has(this.message) && has(this.final))\x1a\x97\x01\n" +
	")agent_up.failed_requires_code_and_message\x12*a failed message requires code and message\x1a>this.type != 'failed' || (has(this.code) && has(this.message))\x1a\xbf\x01\n" +
	"9agent_up.opencode_response_requires_request_id_and_status\x122an opencode_response requires requestId and status\x1aNthis.type != 'opencode_response' || (has(this.request_id) && has(this.status))\x1a\x8b\x01\n" +
	")agent_up.session_idle_requires_live_until\x12)a session_idle message requires liveUntil\x1a3this.type != 'session_idle' || has(this.live_until)\x1a\x83\x01\n" +
	"&agent_up.session_ended_requires_reason\x12'a session_ended message requires reason\x1a0this.type != 'session_ended' || has(this.reason)\x1a\xb7\x01\n" +
	"2agent_up.tool_call_requires_call_id_tool_and_input\x12+a tool_call requires callId, tool and input\x1aTthis.type != 'tool_call' || (has(this.call_id) && has(this.tool) && has(this.input))B\x0f\n" +
	"\r_agent_run_idB\x06\n" +
	"\x04_seqB\x05\n" +
	"\x03_tsB\a\n" +
	"\x05_typeB\b\n" +
	"\x06_stageB\n" +
	"\n" +
	"\b_messageB\x06\n" +
	"\x04_pctB\b\n" +
	"\x06_finalB\a\n" +
	"\x05_codeB\r\n" +
	"\v_request_idB\t\n" +
	"\a_statusB\r\n" +
	"\v_live_untilB\t\n" +
	"\a_reasonB\n" +
	"\n" +
	"\b_call_idB\a\n" +
	"\x05_toolB\b\n" +
	"\x06_input\"\xe3\v\n" +
	"\x10AgentDownMessage\x12/\n" +
	"\fagent_run_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01H\x00R\fagent_run_id\x88\x01\x01\x12\x1d\n" +
	"\x03seq\x18\x02 \x01(\rB\x06\xbaH\x03\xc8\x01\x01H\x01R\x03seq\x88\x01\x01\x12\x1b\n" +
	"\x02ts\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01H\x02R\x02ts\x88\x01\x01\x12c\n" +
	"\x04type\x18\x04 \x01(\tBJ\xbaHG\xc8\x01\x01rBR\x06promptR\x06cancelR\x06signalR\x10opencode_requestR\treply_ackR\vtool_resultH\x03R\x04type\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x05 \x01(\tH\x04R\amessage\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x06 \x01(\tH\x05R\x06reason\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\a \x01(\tH\x06R\x04name\x88\x01\x01\x12*\n" +
	"\x04data\x18\b \x01(\v2\x16.google.protobuf.ValueR\x04data\x12\"\n" +
	"\n" +
	"request_id\x18\t \x01(\tH\aR\trequestId\x88\x01\x01\x12\x1b\n" +
	"\x06method\x18\n" +
	" \x01(\tH\bR\x06method\x88\x01\x01\x12\x17\n" +
	"\x04path\x18\v \x01(\tH\tR\x04path\x88\x01\x01\x12*\n" +
	"\x04body\x18\f \x01(\v2\x16.google.protobuf.ValueR\x04body\x12\x1c\n" +
	"\aack_seq\x18\r \x01(\rH\n" +
	"R\x06ackSeq\x88\x01\x01\x12\x1c\n" +
	"\acall_id\x18\x0e \x01(\tH\vR\x06callId\x88\x01\x01\x12\x13\n" +
	"\x02ok\x18\x0f \x01(\bH\fR\x02ok\x88\x01\x01\x12.\n" +
	"\x06result\x18\x10 \x01(\v2\x16.google.protobuf.ValueR\x06result\x12\x19\n" +
	"\x05error\x18\x11 \x01(\tH\rR\x05error\x88\x01\x01:\xc4\x05\xbaH\xc0\x05\x1ak\n" +
	"\"agent_down.prompt_requires_message\x12\x19a prompt requires message\x1a*this.type != 'prompt' || has(this.message)\x1ab\n" +
	"\x1fagent_down.signal_requires_name\x12\x16a signal requires name\x1a'this.type != 'signal' || has(this.name)\x1a\xdb\x01\n" +
	"?agent_down.opencode_request_requires_request_id_method_and_path\x127an opencode_request requires requestId, method and path\x1a_this.type != 'opencode_request' || (has(this.request_id) && has(this.method) && has(this.path))\x1as\n" +
	"%agent_down.reply_ack_requires_ack_seq\x12\x1ba reply_ack requires ackSeq\x1a-this.type != 'reply_ack' || has(this.ack_seq)\x1a\x99\x01\n" +
	".agent_down.tool_result_requires_call_id_and_ok\x12$a tool_result requires callId and ok\x1aAthis.type != 'tool_result' || (has(this.call_id) && has(this.ok))B\x0f\n" +
	"\r_agent_run_idB\x06\n" +
	"\x04_seqB\x05\n" +
	"\x03_tsB\a\n" +
	"\x05_typeB\n" +
	"\n" +
	"\b_messageB\t\n" +
	"\a_reasonB\a\n" +
	"\x05_nameB\r\n" +
	"\v_request_idB\t\n" +
	"\a_methodB\a\n" +
	"\x05_pathB\n" +
	"\n" +
	"\b_ack_seqB\n" +
	"\n" +
	"\b_call_idB\x05\n" +
	"\x03_okB\b\n" +
	"\x06_errorBdZbgithub.com/imaustink/agent-controller/framework/protocol/go/agentcontroller/protocol/v1;protocolv1b\x06proto3"

var (
	file_agentcontroller_protocol_v1_agent_protocol_proto_rawDescOnce sync.Once
	file_agentcontroller_protocol_v1_agent_protocol_proto_rawDescData []byte
)

func file_agentcontroller_protocol_v1_agent_protocol_proto_rawDescGZIP() []byte {
	file_agentcontroller_protocol_v1_agent_protocol_proto_rawDescOnce.Do(func() {
		file_agentcontroller_protocol_v1_agent_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentcontroller_protocol_v1_agent_protocol_proto_rawDesc), len(file_agentcontroller_protocol_v1_agent_protocol_proto_rawDesc)))
	})
	return file_agentcontroller_protocol_v1_agent_protocol_proto_rawDescData
}

var file_agentcontroller_protocol_v1_agent_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agentcontroller_protocol_v1_agent_protocol_proto_goTypes = []any{
	(*AgentUpMessage)(nil),   // 0: agentcontroller.protocol.v1.AgentUpMessage
	(*AgentDownMessage)(nil), // 1: agentcontroller.protocol.v1.AgentDownMessage
	(*structpb.Value)(nil),   // 2: google.protobuf.Value
}
var file_agentcontroller_protocol_v1_agent_protocol_proto_depIdxs = []int32{
	2, // 0: agentcontroller.protocol.v1.AgentUpMessage.result:type_name -> google.protobuf.Value
	2, // 1: agentcontroller.protocol.v1.AgentUpMessage.event:type_name -> google.protobuf.Value
	2, // 2: agentcontroller.protocol.v1.AgentUpMessage.body:type_name -> google.protobuf.Value
	2, // 3: agentcontroller.protocol.v1.AgentDownMessage.data:type_name -> google.protobuf.Value
	2, // 4: agentcontroller.protocol.v1.AgentDownMessage.body:type_name -> google.protobuf.Value
	2, // 5: agentcontroller.protocol.v1.AgentDownMessage.result:type_name -> google.protobuf.Value
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_agentcontroller_protocol_v1_agent_protocol_proto_init() }
func file_agentcontroller_protocol_v1_agent_protocol_proto_init() {
	if File_agentcontroller_protocol_v1_agent_protocol_proto != nil {
		return
	}
	file_agentcontroller_protocol_v1_agent_protocol_proto_msgTypes[0].OneofWrappers = []any{}
	file_agentcontroller_protocol_v1_agent_protocol_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentcontroller_protocol_v1_agent_protocol_proto_rawDesc), len(file_agentcontroller_protocol_v1_agent_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agentcontroller_protocol_v1_agent_protocol_proto_goTypes,
		DependencyIndexes: file_agentcontroller_protocol_v1_agent_protocol_proto_depIdxs,
		MessageInfos:      file_agentcontroller_protocol_v1_agent_protocol_proto_msgTypes,
	}.Build()
	File_agentcontroller_protocol_v1_agent_protocol_proto = out.File
	file_agentcontroller_protocol_v1_agent_protocol_proto_goTypes = nil
	file_agentcontroller_protocol_v1_agent_protocol_proto_depIdxs = nil
}
