// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agentcontroller/protocol/v1/artifact.proto

package protocolv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reference to a large or binary payload delivered out-of-band (object store,
// mounted volume, etc.). Bytes never travel on an event channel -- only this
// reference does, so the receiver can fetch and verify by hash.
type ArtifactRef struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Uri    *string                `protobuf:"bytes,1,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	Sha256 *string                `protobuf:"bytes,2,opt,name=sha256,proto3,oneof" json:"sha256,omitempty"`
	// A double rather than a 64-bit integer on purpose: proto3 JSON writes
	// int64/uint64 as quoted strings, which would change the wire shape every
	// existing consumer parses as a number. A double is exact to 2^53 bytes.
	Bytes         *float64 `protobuf:"fixed64,3,opt,name=bytes,proto3,oneof" json:"bytes,omitempty"`
	ContentType   *string  `protobuf:"bytes,4,opt,name=content_type,proto3,oneof" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_agentcontroller_protocol_v1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_agentcontroller_protocol_v1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_agentcontroller_protocol_v1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactRef) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *ArtifactRef) GetSha256() string {
	if x != nil && x.Sha256 != nil {
		return *x.Sha256
	}
	return ""
}

func (x *ArtifactRef) GetBytes() float64 {
	if x != nil && x.Bytes != nil {
		return *x.Bytes
	}
	return 0
}

func (x *ArtifactRef) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

var File_agentcontroller_protocol_v1_artifact_proto protoreflect.FileDescriptor

const file_agentcontroller_protocol_v1_artifact_proto_rawDesc = "" +
	"\n" +
	"*agentcontroller/protocol/v1/artifact.proto\x12\x1bagentcontroller.protocol.v1\x1a\x1bbuf/validate/validate.proto\"\xb7\x02\n" +
	"\vArtifactRef\x12\x1d\n" +
	"\x03uri\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01H\x00R\x03uri\x88\x01\x01\x12#\n" +
	"\x06sha256\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01H\x01R\x06sha256\x88\x01\x01\x12\x84\x01\n" +
	"\x05bytes\x18\x03 \x01(\x01Bi\xbaHf\xba\x01U\n" +
	"\x1aartifact_ref.bytes_integer\x12\x1cbytes must be a whole number\x1a\x19this == double(int(this))\xc8\x01\x01\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00H\x02R\x05bytes\x88\x01\x01\x12/\n" +
	"\fcontent_type\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01H\x03R\fcontent_type\x88\x01\x01B\x06\n" +
	"\x04_uriB\t\n" +
	"\a_sha256B\b\n" +
	"\x06_bytesB\x0f\n" +
	"\r_content_typeBdZbgithub.com/imaustink/agent-controller/framework/protocol/go/agentcontroller/protocol/v1;protocolv1b\x06proto3"

var (
	file_agentcontroller_protocol_v1_artifact_proto_rawDescOnce sync.Once
	file_agentcontroller_protocol_v1_artifact_proto_rawDescData []byte
)

func file_agentcontroller_protocol_v1_artifact_proto_rawDescGZIP() []byte {
	file_agentcontroller_protocol_v1_artifact_proto_rawDescOnce.Do(func() {
		file_agentcontroller_protocol_v1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentcontroller_protocol_v1_artifact_proto_rawDesc), len(file_agentcontroller_protocol_v1_artifact_proto_rawDesc)))
	})
	return file_agentcontroller_protocol_v1_artifact_proto_rawDescData
}

var file_agentcontroller_protocol_v1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agentcontroller_protocol_v1_artifact_proto_goTypes = []any{
	(*ArtifactRef)(nil), // 0: agentcontroller.protocol.v1.ArtifactRef
}
var file_agentcontroller_protocol_v1_artifact_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agentcontroller_protocol_v1_artifact_proto_init() }
func file_agentcontroller_protocol_v1_artifact_proto_init() {
	if File_agentcontroller_protocol_v1_artifact_proto != nil {
		return
	}
	file_agentcontroller_protocol_v1_artifact_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentcontroller_protocol_v1_artifact_proto_rawDesc), len(file_agentcontroller_protocol_v1_artifact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agentcontroller_protocol_v1_artifact_proto_goTypes,
		DependencyIndexes: file_agentcontroller_protocol_v1_artifact_proto_depIdxs,
		MessageInfos:      file_agentcontroller_protocol_v1_artifact_proto_msgTypes,
	}.Build()
	File_agentcontroller_protocol_v1_artifact_proto = out.File
	file_agentcontroller_protocol_v1_artifact_proto_goTypes = nil
	file_agentcontroller_protocol_v1_artifact_proto_depIdxs = nil
}
