// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agentcontroller/protocol/v1/event.proto

package protocolv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One event in a TOOL call's one-way stream:
//
//	accepted -> progress* / warning* -> (succeeded | failed)
//
// The same JSON is used on every transport (broker message, NDJSON line, HTTP
// callback body).
//
// Wire shape (ADR 0047): today's JSON is a flat object discriminated by the
// `type` string. proto3 JSON cannot produce that from a oneof (it nests) or an
// enum (it writes EVENT_TYPE_*), so this is ONE flat message: `type` is a
// string, every per-type field is optional with an explicit json_name, and the
// message-level rules below say which fields each type requires. Fields that
// do not belong to a type are tolerated, not rejected, matching the receivers
// that have always ignored them.
//
// `result`, `stage` and `code` are deliberately loose: a tool owns the shape of
// its own result and the vocabulary of its own stages and failure codes. The
// shared contract is the envelope.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation id shared by every event of a single tool call.
	JobId *string `protobuf:"bytes,1,opt,name=job_id,proto3,oneof" json:"job_id,omitempty"`
	// Monotonic per-job sequence number; gives ordering and dedupe.
	Seq *uint32 `protobuf:"varint,2,opt,name=seq,proto3,oneof" json:"seq,omitempty"`
	// ISO 8601 emission timestamp.
	Ts   *string `protobuf:"bytes,3,opt,name=ts,proto3,oneof" json:"ts,omitempty"`
	Type *string `protobuf:"bytes,4,opt,name=type,proto3,oneof" json:"type,omitempty"`
	// accepted: where the caller can poll or follow the job.
	Url *string `protobuf:"bytes,5,opt,name=url,proto3,oneof" json:"url,omitempty"`
	// progress: a tool-defined pipeline stage, and an optional completion
	// percentage.
	Stage *string  `protobuf:"bytes,6,opt,name=stage,proto3,oneof" json:"stage,omitempty"`
	Pct   *float64 `protobuf:"fixed64,7,opt,name=pct,proto3,oneof" json:"pct,omitempty"`
	// progress / warning / failed.
	Message *string `protobuf:"bytes,8,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// succeeded: whatever the tool produces (any JSON value), plus references to
	// anything too large to inline.
	Result    *structpb.Value `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	Artifacts []*ArtifactRef  `protobuf:"bytes,10,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	// failed: a tool-defined failure code.
	Code          *string `protobuf:"bytes,11,opt,name=code,proto3,oneof" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_agentcontroller_protocol_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_agentcontroller_protocol_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_agentcontroller_protocol_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

func (x *Event) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *Event) GetTs() string {
	if x != nil && x.Ts != nil {
		return *x.Ts
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Event) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Event) GetStage() string {
	if x != nil && x.Stage != nil {
		return *x.Stage
	}
	return ""
}

func (x *Event) GetPct() float64 {
	if x != nil && x.Pct != nil {
		return *x.Pct
	}
	return 0
}

func (x *Event) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *Event) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Event) GetArtifacts() []*ArtifactRef {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Event) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

var File_agentcontroller_protocol_v1_event_proto protoreflect.FileDescriptor

const file_agentcontroller_protocol_v1_event_proto_rawDesc = "" +
	"\n" +
	"'agentcontroller/protocol/v1/event.proto\x12\x1bagentcontroller.protocol.v1\x1a*agentcontroller/protocol/v1/artifact.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf7\b\n" +
	"\x05Event\x12#\n" +
	"\x06job_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01H\x00R\x06job_id\x88\x01\x01\x12\x1d\n" +
	"\x03seq\x18\x02 \x01(\rB\x06\xbaH\x03\xc8\x01\x01H\x01R\x03seq\x88\x01\x01\x12\x1b\n" +
	"\x02ts\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01H\x02R\x02ts\x88\x01\x01\x12Q\n" +
	"\x04type\x18\x04 \x01(\tB8\xbaH5\xc8\x01\x01r0R\bacceptedR\bprogressR\awarningR\tsucceededR\x06failedH\x03R\x04type\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x05 \x01(\tH\x04R\x03url\x88\x01\x01\x12\x19\n" +
	"\x05stage\x18\x06 \x01(\tH\x05R\x05stage\x88\x01\x01\x12.\n" +
	"\x03pct\x18\a \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00Y@)\x00\x00\x00\x00\x00\x00\x00\x00H\x06R\x03pct\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\b \x01(\tH\aR\amessage\x88\x01\x01\x12.\n" +
	"\x06result\x18\t \x01(\v2\x16.google.protobuf.ValueR\x06result\x12F\n" +
	"\tartifacts\x18\n" +
	" \x03(\v2(.agentcontroller.protocol.v1.ArtifactRefR\tartifacts\x12\x17\n" +
	"\x04code\x18\v \x01(\tH\bR\x04code\x88\x01\x01:\xd5\x04\xbaH\xd1\x04\x1ag\n" +
	"\x1bevent.accepted_requires_url\x12\x1ean accepted event requires url\x1a(this.type != 'accepted' || has(this.url)\x1al\n" +
	"\x1devent.progress_requires_stage\x12\x1fa progress event requires stage\x1a*this.type != 'progress' || has(this.stage)\x1ao\n" +
	"\x1eevent.warning_requires_message\x12 a warning event requires message\x1a+this.type != 'warning' || has(this.message)\x1ar\n" +
	"\x1fevent.succeeded_requires_result\x12!a succeeded event requires result\x1a,this.type != 'succeeded' || has(this.result)\x1a\x92\x01\n" +
	"&event.failed_requires_code_and_message\x12(a failed event requires code and message\x1a>this.type != 'failed' || (has(this.code) && has(this.message))B\t\n" +
	"\a_job_idB\x06\n" +
	"\x04_seqB\x05\n" +
	"\x03_tsB\a\n" +
	"\x05_typeB\x06\n" +
	"\x04_urlB\b\n" +
	"\x06_stageB\x06\n" +
	"\x04_pctB\n" +
	"\n" +
	"\b_messageB\a\n" +
	"\x05_codeBdZbgithub.com/imaustink/agent-controller/framework/protocol/go/agentcontroller/protocol/v1;protocolv1b\x06proto3"

var (
	file_agentcontroller_protocol_v1_event_proto_rawDescOnce sync.Once
	file_agentcontroller_protocol_v1_event_proto_rawDescData []byte
)

func file_agentcontroller_protocol_v1_event_proto_rawDescGZIP() []byte {
	file_agentcontroller_protocol_v1_event_proto_rawDescOnce.Do(func() {
		file_agentcontroller_protocol_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentcontroller_protocol_v1_event_proto_rawDesc), len(file_agentcontroller_protocol_v1_event_proto_rawDesc)))
	})
	return file_agentcontroller_protocol_v1_event_proto_rawDescData
}

var file_agentcontroller_protocol_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agentcontroller_protocol_v1_event_proto_goTypes = []any{
	(*Event)(nil),          // 0: agentcontroller.protocol.v1.Event
	(*structpb.Value)(nil), // 1: google.protobuf.Value
	(*ArtifactRef)(nil),    // 2: agentcontroller.protocol.v1.ArtifactRef
}
var file_agentcontroller_protocol_v1_event_proto_depIdxs = []int32{
	1, // 0: agentcontroller.protocol.v1.Event.result:type_name -> google.protobuf.Value
	2, // 1: agentcontroller.protocol.v1.Event.artifacts:type_name -> agentcontroller.protocol.v1.ArtifactRef
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agentcontroller_protocol_v1_event_proto_init() }
func file_agentcontroller_protocol_v1_event_proto_init() {
	if File_agentcontroller_protocol_v1_event_proto != nil {
		return
	}
	file_agentcontroller_protocol_v1_artifact_proto_init()
	file_agentcontroller_protocol_v1_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentcontroller_protocol_v1_event_proto_rawDesc), len(file_agentcontroller_protocol_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agentcontroller_protocol_v1_event_proto_goTypes,
		DependencyIndexes: file_agentcontroller_protocol_v1_event_proto_depIdxs,
		MessageInfos:      file_agentcontroller_protocol_v1_event_proto_msgTypes,
	}.Build()
	File_agentcontroller_protocol_v1_event_proto = out.File
	file_agentcontroller_protocol_v1_event_proto_goTypes = nil
	file_agentcontroller_protocol_v1_event_proto_depIdxs = nil
}
