// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agentcontroller/protocol/v1/turn_event.proto

package protocolv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One point in a TURN's lifecycle (temporal engine ADR 0004).
//
// Where Event is one tool call's stream, a TurnEvent is the envelope an
// orchestrator narrates over a whole turn: a skill was selected, a tool
// started / progressed / finished / failed, a warning, the two approval-gate
// transitions (temporal engine ADR 0003), free-text narration, and the turn
// boundaries. Both engines render each one to the status line clients already
// receive, so adopting it changed no client-visible text.
//
// Field names are camelCase on the wire (`skillId`, `toolId`). Until this
// contract existed the Go engine wrote `skill_id`/`tool_id` while TypeScript
// wrote `skillId`/`toolId`; the JSON had not yet reached a client, so this
// contract settles on the TypeScript spelling (ADR 0047).
type TurnEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic per-turn sequence number; gives ordering and dedupe.
	Seq *uint32 `protobuf:"varint,1,opt,name=seq,proto3,oneof" json:"seq,omitempty"`
	// ISO 8601 emission timestamp.
	Ts      *string  `protobuf:"bytes,2,opt,name=ts,proto3,oneof" json:"ts,omitempty"`
	Kind    *string  `protobuf:"bytes,3,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	SkillId *string  `protobuf:"bytes,4,opt,name=skill_id,json=skillId,proto3,oneof" json:"skill_id,omitempty"`
	ToolId  *string  `protobuf:"bytes,5,opt,name=tool_id,json=toolId,proto3,oneof" json:"tool_id,omitempty"`
	Stage   *string  `protobuf:"bytes,6,opt,name=stage,proto3,oneof" json:"stage,omitempty"`
	Pct     *float64 `protobuf:"fixed64,7,opt,name=pct,proto3,oneof" json:"pct,omitempty"`
	// approval-resolved carries the decision here (e.g. "approved", "denied");
	// tool-failed carries the tool's failure code.
	Code          *string        `protobuf:"bytes,8,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Message       *string        `protobuf:"bytes,9,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Artifacts     []*ArtifactRef `protobuf:"bytes,10,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnEvent) Reset() {
	*x = TurnEvent{}
	mi := &file_agentcontroller_protocol_v1_turn_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnEvent) ProtoMessage() {}

func (x *TurnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agentcontroller_protocol_v1_turn_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnEvent.ProtoReflect.Descriptor instead.
func (*TurnEvent) Descriptor() ([]byte, []int) {
	return file_agentcontroller_protocol_v1_turn_event_proto_rawDescGZIP(), []int{0}
}

func (x *TurnEvent) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *TurnEvent) GetTs() string {
	if x != nil && x.Ts != nil {
		return *x.Ts
	}
	return ""
}

func (x *TurnEvent) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *TurnEvent) GetSkillId() string {
	if x != nil && x.SkillId != nil {
		return *x.SkillId
	}
	return ""
}

func (x *TurnEvent) GetToolId() string {
	if x != nil && x.ToolId != nil {
		return *x.ToolId
	}
	return ""
}

func (x *TurnEvent) GetStage() string {
	if x != nil && x.Stage != nil {
		return *x.Stage
	}
	return ""
}

func (x *TurnEvent) GetPct() float64 {
	if x != nil && x.Pct != nil {
		return *x.Pct
	}
	return 0
}

func (x *TurnEvent) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *TurnEvent) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *TurnEvent) GetArtifacts() []*ArtifactRef {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

var File_agentcontroller_protocol_v1_turn_event_proto protoreflect.FileDescriptor

const file_agentcontroller_protocol_v1_turn_event_proto_rawDesc = "" +
	"\n" +
	",agentcontroller/protocol/v1/turn_event.proto\x12\x1bagentcontroller.protocol.v1\x1a*agentcontroller/protocol/v1/artifact.proto\x1a\x1bbuf/validate/validate.proto\"\xf0\x04\n" +
	"\tTurnEvent\x12\x1d\n" +
	"\x03seq\x18\x01 \x01(\rB\x06\xbaH\x03\xc8\x01\x01H\x00R\x03seq\x88\x01\x01\x12\x1b\n" +
	"\x02ts\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01H\x01R\x02ts\x88\x01\x01\x12\xc5\x01\n" +
	"\x04kind\x18\x03 \x01(\tB\xab\x01\xbaH\xa7\x01\xc8\x01\x01r\xa1\x01R\fturn-startedR\x0eskill-selectedR\ftool-startedR\rtool-progressR\rtool-finishedR\vtool-failedR\awarningR\x11approval-requiredR\x11approval-resolvedR\x0eturn-completedR\tnarrationH\x02R\x04kind\x88\x01\x01\x12\x1e\n" +
	"\bskill_id\x18\x04 \x01(\tH\x03R\askillId\x88\x01\x01\x12\x1c\n" +
	"\atool_id\x18\x05 \x01(\tH\x04R\x06toolId\x88\x01\x01\x12\x19\n" +
	"\x05stage\x18\x06 \x01(\tH\x05R\x05stage\x88\x01\x01\x12.\n" +
	"\x03pct\x18\a \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00Y@)\x00\x00\x00\x00\x00\x00\x00\x00H\x06R\x03pct\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\b \x01(\tH\aR\x04code\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\t \x01(\tH\bR\amessage\x88\x01\x01\x12F\n" +
	"\tartifacts\x18\n" +
	" \x03(\v2(.agentcontroller.protocol.v1.ArtifactRefR\tartifactsB\x06\n" +
	"\x04_seqB\x05\n" +
	"\x03_tsB\a\n" +
	"\x05_kindB\v\n" +
	"\t_skill_idB\n" +
	"\n" +
	"\b_tool_idB\b\n" +
	"\x06_stageB\x06\n" +
	"\x04_pctB\a\n" +
	"\x05_codeB\n" +
	"\n" +
	"\b_messageBdZbgithub.com/imaustink/agent-controller/framework/protocol/go/agentcontroller/protocol/v1;protocolv1b\x06proto3"

var (
	file_agentcontroller_protocol_v1_turn_event_proto_rawDescOnce sync.Once
	file_agentcontroller_protocol_v1_turn_event_proto_rawDescData []byte
)

func file_agentcontroller_protocol_v1_turn_event_proto_rawDescGZIP() []byte {
	file_agentcontroller_protocol_v1_turn_event_proto_rawDescOnce.Do(func() {
		file_agentcontroller_protocol_v1_turn_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentcontroller_protocol_v1_turn_event_proto_rawDesc), len(file_agentcontroller_protocol_v1_turn_event_proto_rawDesc)))
	})
	return file_agentcontroller_protocol_v1_turn_event_proto_rawDescData
}

var file_agentcontroller_protocol_v1_turn_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agentcontroller_protocol_v1_turn_event_proto_goTypes = []any{
	(*TurnEvent)(nil),   // 0: agentcontroller.protocol.v1.TurnEvent
	(*ArtifactRef)(nil), // 1: agentcontroller.protocol.v1.ArtifactRef
}
var file_agentcontroller_protocol_v1_turn_event_proto_depIdxs = []int32{
	1, // 0: agentcontroller.protocol.v1.TurnEvent.artifacts:type_name -> agentcontroller.protocol.v1.ArtifactRef
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agentcontroller_protocol_v1_turn_event_proto_init() }
func file_agentcontroller_protocol_v1_turn_event_proto_init() {
	if File_agentcontroller_protocol_v1_turn_event_proto != nil {
		return
	}
	file_agentcontroller_protocol_v1_artifact_proto_init()
	file_agentcontroller_protocol_v1_turn_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentcontroller_protocol_v1_turn_event_proto_rawDesc), len(file_agentcontroller_protocol_v1_turn_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agentcontroller_protocol_v1_turn_event_proto_goTypes,
		DependencyIndexes: file_agentcontroller_protocol_v1_turn_event_proto_depIdxs,
		MessageInfos:      file_agentcontroller_protocol_v1_turn_event_proto_msgTypes,
	}.Build()
	File_agentcontroller_protocol_v1_turn_event_proto = out.File
	file_agentcontroller_protocol_v1_turn_event_proto_goTypes = nil
	file_agentcontroller_protocol_v1_turn_event_proto_depIdxs = nil
}
