/**
 * The DOM-free half of the renderer: given a values object and a schema, produce
 * the YAML the form would have submitted.
 *
 * This exists so scripts/helm-check.mjs can drive the real prune and the real
 * emitter from Node and hand the result to Helm. A test harness that
 * reimplemented either one would happily pass while the shipped code was broken.
 */

import { pruneToOverrides } from "./prune.js";
import { emitYaml } from "./yaml.js";
import type { Json, JSONSchema } from "./types.js";

export { pruneToOverrides, resolveRef, typeOf, deepEqual, resolvePath } from "./prune.js";
export { emitYaml, needsQuotes } from "./yaml.js";

export interface ValuesOptions {
  chart: string;
  chartVersion?: string;
}

/**
 * Mirrors what render.ts does on a valid submit: prune against the schema, then
 * emit with the same generated-by header.
 */
export function valuesYaml(
  values: Record<string, Json>,
  schema: JSONSchema,
  opts: ValuesOptions,
): { yaml: string; overrides: Record<string, Json> } {
  const overrides = pruneToOverrides(values, schema);
  const header = [`Generated by helm-values-form for chart: ${opts.chart}`];
  const version = opts.chartVersion ?? (typeof schema.version === "string" ? schema.version : null);
  if (version) header.push(`Schema version: ${version}`);
  header.push("Only values that differ from the chart defaults are listed.");
  if (Object.keys(overrides).length === 0) {
    header.push("No overrides: every field was left at its chart default.");
  }
  return { yaml: emitYaml(overrides, { header }), overrides };
}
