{{- range .Values.onePasswordItems }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "durable-agents.labels" $ | nindent 4 }}
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: {{ .itemPath | quote }}
---
{{- end }}
