---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - core.controller-agent.dev
  resources:
  - agentruns
  - agents
  - localtools
  - skills
  - toolruns
  - tools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.controller-agent.dev
  resources:
  - agentruns/finalizers
  - agents/finalizers
  - localtools/finalizers
  - skills/finalizers
  - toolruns/finalizers
  - tools/finalizers
  verbs:
  - update
- apiGroups:
  - core.controller-agent.dev
  resources:
  - agentruns/status
  - agents/status
  - localtools/status
  - skills/status
  - toolruns/status
  - tools/status
  verbs:
  - get
  - patch
  - update
